// Code generated by protoc-gen-go. DO NOT EDIT.
// source: currency.proto

/*
Package curproto is a generated protocol buffer package.

It is generated from these files:
	currency.proto

It has these top-level messages:
	Currency
	CurrencyList
	CurrencyRequest
*/
package curproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Currency represents currency information
type Currency struct {
	Code    string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Number  int32  `protobuf:"varint,3,opt,name=number" json:"number,omitempty"`
	Country string `protobuf:"bytes,4,opt,name=country" json:"country,omitempty"`
}

func (m *Currency) Reset()                    { *m = Currency{} }
func (m *Currency) String() string            { return proto.CompactTextString(m) }
func (*Currency) ProtoMessage()               {}
func (*Currency) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Currency) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Currency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Currency) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Currency) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

// CurrencyList used for list of currencies
type CurrencyList struct {
	Items []*Currency `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *CurrencyList) Reset()                    { *m = CurrencyList{} }
func (m *CurrencyList) String() string            { return proto.CompactTextString(m) }
func (*CurrencyList) ProtoMessage()               {}
func (*CurrencyList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CurrencyList) GetItems() []*Currency {
	if m != nil {
		return m.Items
	}
	return nil
}

// CurrencyRequest used to request currency
type CurrencyRequest struct {
	Code   string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Number int32  `protobuf:"varint,2,opt,name=number" json:"number,omitempty"`
}

func (m *CurrencyRequest) Reset()                    { *m = CurrencyRequest{} }
func (m *CurrencyRequest) String() string            { return proto.CompactTextString(m) }
func (*CurrencyRequest) ProtoMessage()               {}
func (*CurrencyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CurrencyRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CurrencyRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*Currency)(nil), "curproto.Currency")
	proto.RegisterType((*CurrencyList)(nil), "curproto.CurrencyList")
	proto.RegisterType((*CurrencyRequest)(nil), "curproto.CurrencyRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CurrencyService service

type CurrencyServiceClient interface {
	// GetCurrencyList  returns matching Currency values as list
	GetCurrencyList(ctx context.Context, in *CurrencyRequest, opts ...grpc.CallOption) (*CurrencyList, error)
	// GetCurrencyStream returns matching Currencies as a server stream
	GetCurrencyStream(ctx context.Context, in *CurrencyRequest, opts ...grpc.CallOption) (CurrencyService_GetCurrencyStreamClient, error)
}

type currencyServiceClient struct {
	cc *grpc.ClientConn
}

func NewCurrencyServiceClient(cc *grpc.ClientConn) CurrencyServiceClient {
	return &currencyServiceClient{cc}
}

func (c *currencyServiceClient) GetCurrencyList(ctx context.Context, in *CurrencyRequest, opts ...grpc.CallOption) (*CurrencyList, error) {
	out := new(CurrencyList)
	err := grpc.Invoke(ctx, "/curproto.CurrencyService/GetCurrencyList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) GetCurrencyStream(ctx context.Context, in *CurrencyRequest, opts ...grpc.CallOption) (CurrencyService_GetCurrencyStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CurrencyService_serviceDesc.Streams[0], c.cc, "/curproto.CurrencyService/GetCurrencyStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &currencyServiceGetCurrencyStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CurrencyService_GetCurrencyStreamClient interface {
	Recv() (*Currency, error)
	grpc.ClientStream
}

type currencyServiceGetCurrencyStreamClient struct {
	grpc.ClientStream
}

func (x *currencyServiceGetCurrencyStreamClient) Recv() (*Currency, error) {
	m := new(Currency)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for CurrencyService service

type CurrencyServiceServer interface {
	// GetCurrencyList  returns matching Currency values as list
	GetCurrencyList(context.Context, *CurrencyRequest) (*CurrencyList, error)
	// GetCurrencyStream returns matching Currencies as a server stream
	GetCurrencyStream(*CurrencyRequest, CurrencyService_GetCurrencyStreamServer) error
}

func RegisterCurrencyServiceServer(s *grpc.Server, srv CurrencyServiceServer) {
	s.RegisterService(&_CurrencyService_serviceDesc, srv)
}

func _CurrencyService_GetCurrencyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).GetCurrencyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/curproto.CurrencyService/GetCurrencyList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).GetCurrencyList(ctx, req.(*CurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_GetCurrencyStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CurrencyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CurrencyServiceServer).GetCurrencyStream(m, &currencyServiceGetCurrencyStreamServer{stream})
}

type CurrencyService_GetCurrencyStreamServer interface {
	Send(*Currency) error
	grpc.ServerStream
}

type currencyServiceGetCurrencyStreamServer struct {
	grpc.ServerStream
}

func (x *currencyServiceGetCurrencyStreamServer) Send(m *Currency) error {
	return x.ServerStream.SendMsg(m)
}

var _CurrencyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "curproto.CurrencyService",
	HandlerType: (*CurrencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrencyList",
			Handler:    _CurrencyService_GetCurrencyList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCurrencyStream",
			Handler:       _CurrencyService_GetCurrencyStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "currency.proto",
}

func init() { proto.RegisterFile("currency.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0xbf, 0x4e, 0x03, 0x31,
	0x0c, 0xc6, 0x9b, 0xfe, 0xa3, 0x18, 0x44, 0x85, 0x87, 0x2a, 0x30, 0x9d, 0x32, 0x65, 0x3a, 0xa1,
	0xb2, 0xb0, 0x30, 0x21, 0x95, 0x85, 0xe9, 0xfa, 0x04, 0x6d, 0xea, 0xe1, 0x86, 0x24, 0xe0, 0x4b,
	0x90, 0xfa, 0x38, 0xbc, 0x29, 0xba, 0x5c, 0x43, 0x0f, 0x71, 0x62, 0xfb, 0xfc, 0xf9, 0xb3, 0xfd,
	0x33, 0xdc, 0x98, 0xc8, 0x4c, 0xce, 0x1c, 0xcb, 0x77, 0xf6, 0xc1, 0xe3, 0xc2, 0x44, 0x4e, 0x4a,
	0x1d, 0x60, 0xf1, 0x72, 0xea, 0x21, 0xc2, 0xd4, 0xf8, 0x03, 0x49, 0x51, 0x08, 0x7d, 0x59, 0x25,
	0xdd, 0x7a, 0x6e, 0x67, 0x49, 0x8e, 0x3b, 0xaf, 0xd5, 0xb8, 0x82, 0xb9, 0x8b, 0x76, 0x4f, 0x2c,
	0x27, 0x85, 0xd0, 0xb3, 0xea, 0x54, 0xa1, 0x84, 0x0b, 0xe3, 0xa3, 0x0b, 0x7c, 0x94, 0xd3, 0x14,
	0xcf, 0xa5, 0x7a, 0x82, 0xeb, 0x7c, 0xe5, 0xad, 0x6e, 0x02, 0x6a, 0x98, 0xd5, 0x81, 0x6c, 0x23,
	0x45, 0x31, 0xd1, 0x57, 0x6b, 0x2c, 0x33, 0x4f, 0x99, 0x63, 0x55, 0x17, 0x50, 0xcf, 0xb0, 0xfc,
	0xb1, 0xe8, 0x23, 0x52, 0x13, 0x06, 0x31, 0xcf, 0x48, 0xe3, 0x3e, 0xd2, 0xfa, 0x4b, 0x9c, 0xe7,
	0xb7, 0xc4, 0x9f, 0xb5, 0x21, 0xdc, 0xc0, 0xf2, 0x95, 0xc2, 0x2f, 0x9e, 0xbb, 0x01, 0x80, 0xee,
	0xda, 0xfd, 0xea, 0x6f, 0xab, 0x1d, 0x51, 0x23, 0xdc, 0xc0, 0x6d, 0x6f, 0xcf, 0x36, 0x30, 0xed,
	0xec, 0x7f, 0x9b, 0x06, 0xbe, 0x54, 0xa3, 0x07, 0xb1, 0x9f, 0x27, 0xef, 0xf1, 0x3b, 0x00, 0x00,
	0xff, 0xff, 0x0b, 0xda, 0xd4, 0x49, 0xa5, 0x01, 0x00, 0x00,
}
