// Code generated by protoc-gen-go. DO NOT EDIT.
// source: currency.proto

/*
Package curproto is a generated protocol buffer package.

It is generated from these files:
	currency.proto

It has these top-level messages:
	Currency
	CurrencyList
	CurrencyRequest
*/
package curproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Currency represents currency information
type Currency struct {
	Code    string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Number  int32  `protobuf:"varint,3,opt,name=number" json:"number,omitempty"`
	Country string `protobuf:"bytes,4,opt,name=country" json:"country,omitempty"`
}

func (m *Currency) Reset()                    { *m = Currency{} }
func (m *Currency) String() string            { return proto.CompactTextString(m) }
func (*Currency) ProtoMessage()               {}
func (*Currency) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Currency) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Currency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Currency) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Currency) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

// CurrencyList used for list of currencies
type CurrencyList struct {
	Items []*Currency `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *CurrencyList) Reset()                    { *m = CurrencyList{} }
func (m *CurrencyList) String() string            { return proto.CompactTextString(m) }
func (*CurrencyList) ProtoMessage()               {}
func (*CurrencyList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CurrencyList) GetItems() []*Currency {
	if m != nil {
		return m.Items
	}
	return nil
}

// CurrencyRequest used to request currency
type CurrencyRequest struct {
	Code   string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Number int32  `protobuf:"varint,2,opt,name=number" json:"number,omitempty"`
}

func (m *CurrencyRequest) Reset()                    { *m = CurrencyRequest{} }
func (m *CurrencyRequest) String() string            { return proto.CompactTextString(m) }
func (*CurrencyRequest) ProtoMessage()               {}
func (*CurrencyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CurrencyRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CurrencyRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*Currency)(nil), "curproto.Currency")
	proto.RegisterType((*CurrencyList)(nil), "curproto.CurrencyList")
	proto.RegisterType((*CurrencyRequest)(nil), "curproto.CurrencyRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CurrencyService service

type CurrencyServiceClient interface {
	// GetCurrencyList  returns matching Currency values as list
	// Example of a unary call
	GetCurrencyList(ctx context.Context, in *CurrencyRequest, opts ...grpc.CallOption) (*CurrencyList, error)
	// GetCurrencyStream returns matching Currencies as a server stream
	// Example of using server to client stream.
	GetCurrencyStream(ctx context.Context, in *CurrencyRequest, opts ...grpc.CallOption) (CurrencyService_GetCurrencyStreamClient, error)
	// SaveCurrencyStream sends multiple currencies to server to be saved
	// returns a list of saved currency.
	// Example of using client stream to server.
	SaveCurrencyStream(ctx context.Context, opts ...grpc.CallOption) (CurrencyService_SaveCurrencyStreamClient, error)
	// FindCurrencyStream sends a stream of CurrencyRequest to server and returns
	// a stream of Currency values.
	// Example of bi-directional stream
	FindCurrencyStream(ctx context.Context, opts ...grpc.CallOption) (CurrencyService_FindCurrencyStreamClient, error)
}

type currencyServiceClient struct {
	cc *grpc.ClientConn
}

func NewCurrencyServiceClient(cc *grpc.ClientConn) CurrencyServiceClient {
	return &currencyServiceClient{cc}
}

func (c *currencyServiceClient) GetCurrencyList(ctx context.Context, in *CurrencyRequest, opts ...grpc.CallOption) (*CurrencyList, error) {
	out := new(CurrencyList)
	err := grpc.Invoke(ctx, "/curproto.CurrencyService/GetCurrencyList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) GetCurrencyStream(ctx context.Context, in *CurrencyRequest, opts ...grpc.CallOption) (CurrencyService_GetCurrencyStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CurrencyService_serviceDesc.Streams[0], c.cc, "/curproto.CurrencyService/GetCurrencyStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &currencyServiceGetCurrencyStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CurrencyService_GetCurrencyStreamClient interface {
	Recv() (*Currency, error)
	grpc.ClientStream
}

type currencyServiceGetCurrencyStreamClient struct {
	grpc.ClientStream
}

func (x *currencyServiceGetCurrencyStreamClient) Recv() (*Currency, error) {
	m := new(Currency)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *currencyServiceClient) SaveCurrencyStream(ctx context.Context, opts ...grpc.CallOption) (CurrencyService_SaveCurrencyStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CurrencyService_serviceDesc.Streams[1], c.cc, "/curproto.CurrencyService/SaveCurrencyStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &currencyServiceSaveCurrencyStreamClient{stream}
	return x, nil
}

type CurrencyService_SaveCurrencyStreamClient interface {
	Send(*Currency) error
	CloseAndRecv() (*CurrencyList, error)
	grpc.ClientStream
}

type currencyServiceSaveCurrencyStreamClient struct {
	grpc.ClientStream
}

func (x *currencyServiceSaveCurrencyStreamClient) Send(m *Currency) error {
	return x.ClientStream.SendMsg(m)
}

func (x *currencyServiceSaveCurrencyStreamClient) CloseAndRecv() (*CurrencyList, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(CurrencyList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *currencyServiceClient) FindCurrencyStream(ctx context.Context, opts ...grpc.CallOption) (CurrencyService_FindCurrencyStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CurrencyService_serviceDesc.Streams[2], c.cc, "/curproto.CurrencyService/FindCurrencyStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &currencyServiceFindCurrencyStreamClient{stream}
	return x, nil
}

type CurrencyService_FindCurrencyStreamClient interface {
	Send(*CurrencyRequest) error
	Recv() (*Currency, error)
	grpc.ClientStream
}

type currencyServiceFindCurrencyStreamClient struct {
	grpc.ClientStream
}

func (x *currencyServiceFindCurrencyStreamClient) Send(m *CurrencyRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *currencyServiceFindCurrencyStreamClient) Recv() (*Currency, error) {
	m := new(Currency)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for CurrencyService service

type CurrencyServiceServer interface {
	// GetCurrencyList  returns matching Currency values as list
	// Example of a unary call
	GetCurrencyList(context.Context, *CurrencyRequest) (*CurrencyList, error)
	// GetCurrencyStream returns matching Currencies as a server stream
	// Example of using server to client stream.
	GetCurrencyStream(*CurrencyRequest, CurrencyService_GetCurrencyStreamServer) error
	// SaveCurrencyStream sends multiple currencies to server to be saved
	// returns a list of saved currency.
	// Example of using client stream to server.
	SaveCurrencyStream(CurrencyService_SaveCurrencyStreamServer) error
	// FindCurrencyStream sends a stream of CurrencyRequest to server and returns
	// a stream of Currency values.
	// Example of bi-directional stream
	FindCurrencyStream(CurrencyService_FindCurrencyStreamServer) error
}

func RegisterCurrencyServiceServer(s *grpc.Server, srv CurrencyServiceServer) {
	s.RegisterService(&_CurrencyService_serviceDesc, srv)
}

func _CurrencyService_GetCurrencyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).GetCurrencyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/curproto.CurrencyService/GetCurrencyList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).GetCurrencyList(ctx, req.(*CurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_GetCurrencyStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CurrencyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CurrencyServiceServer).GetCurrencyStream(m, &currencyServiceGetCurrencyStreamServer{stream})
}

type CurrencyService_GetCurrencyStreamServer interface {
	Send(*Currency) error
	grpc.ServerStream
}

type currencyServiceGetCurrencyStreamServer struct {
	grpc.ServerStream
}

func (x *currencyServiceGetCurrencyStreamServer) Send(m *Currency) error {
	return x.ServerStream.SendMsg(m)
}

func _CurrencyService_SaveCurrencyStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CurrencyServiceServer).SaveCurrencyStream(&currencyServiceSaveCurrencyStreamServer{stream})
}

type CurrencyService_SaveCurrencyStreamServer interface {
	SendAndClose(*CurrencyList) error
	Recv() (*Currency, error)
	grpc.ServerStream
}

type currencyServiceSaveCurrencyStreamServer struct {
	grpc.ServerStream
}

func (x *currencyServiceSaveCurrencyStreamServer) SendAndClose(m *CurrencyList) error {
	return x.ServerStream.SendMsg(m)
}

func (x *currencyServiceSaveCurrencyStreamServer) Recv() (*Currency, error) {
	m := new(Currency)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CurrencyService_FindCurrencyStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CurrencyServiceServer).FindCurrencyStream(&currencyServiceFindCurrencyStreamServer{stream})
}

type CurrencyService_FindCurrencyStreamServer interface {
	Send(*Currency) error
	Recv() (*CurrencyRequest, error)
	grpc.ServerStream
}

type currencyServiceFindCurrencyStreamServer struct {
	grpc.ServerStream
}

func (x *currencyServiceFindCurrencyStreamServer) Send(m *Currency) error {
	return x.ServerStream.SendMsg(m)
}

func (x *currencyServiceFindCurrencyStreamServer) Recv() (*CurrencyRequest, error) {
	m := new(CurrencyRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CurrencyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "curproto.CurrencyService",
	HandlerType: (*CurrencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrencyList",
			Handler:    _CurrencyService_GetCurrencyList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCurrencyStream",
			Handler:       _CurrencyService_GetCurrencyStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SaveCurrencyStream",
			Handler:       _CurrencyService_SaveCurrencyStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FindCurrencyStream",
			Handler:       _CurrencyService_FindCurrencyStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "currency.proto",
}

func init() { proto.RegisterFile("currency.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x8f, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xeb, 0xf4, 0x0f, 0xe5, 0x40, 0x54, 0xdc, 0x50, 0x19, 0xa6, 0xc8, 0x93, 0xa7, 0xa8,
	0x2a, 0x0b, 0x0b, 0x13, 0x28, 0x08, 0x89, 0x29, 0xf9, 0x04, 0xa9, 0x73, 0x43, 0x86, 0x38, 0x70,
	0xb1, 0x2b, 0xf5, 0x6b, 0xf1, 0x09, 0x51, 0x92, 0x86, 0x16, 0x08, 0x2c, 0xdd, 0x9e, 0xdf, 0xbd,
	0x7b, 0xf7, 0x33, 0x5c, 0x19, 0xcf, 0x4c, 0xd6, 0xec, 0xa2, 0x37, 0xae, 0x5c, 0x85, 0x73, 0xe3,
	0xb9, 0x55, 0x2a, 0x87, 0xf9, 0xe3, 0x7e, 0x86, 0x08, 0x13, 0x53, 0xe5, 0x24, 0x45, 0x28, 0xf4,
	0x79, 0xd2, 0xea, 0xc6, 0xb3, 0x59, 0x49, 0x32, 0xe8, 0xbc, 0x46, 0xe3, 0x12, 0x66, 0xd6, 0x97,
	0x1b, 0x62, 0x39, 0x0e, 0x85, 0x9e, 0x26, 0xfb, 0x17, 0x4a, 0x38, 0x33, 0x95, 0xb7, 0x8e, 0x77,
	0x72, 0xd2, 0xc6, 0xfb, 0xa7, 0xba, 0x87, 0xcb, 0xfe, 0xca, 0x6b, 0x51, 0x3b, 0xd4, 0x30, 0x2d,
	0x1c, 0x95, 0xb5, 0x14, 0xe1, 0x58, 0x5f, 0xac, 0x31, 0xea, 0x79, 0xa2, 0x3e, 0x96, 0x74, 0x01,
	0xf5, 0x00, 0x8b, 0x2f, 0x8b, 0xde, 0x3d, 0xd5, 0x6e, 0x10, 0xf3, 0x80, 0x14, 0x1c, 0x23, 0xad,
	0x3f, 0x82, 0xc3, 0x7e, 0x4a, 0xbc, 0x2d, 0x0c, 0x61, 0x0c, 0x8b, 0x67, 0x72, 0xdf, 0x78, 0x6e,
	0x06, 0x00, 0xba, 0x6b, 0xb7, 0xcb, 0xdf, 0xa3, 0x66, 0x45, 0x8d, 0x30, 0x86, 0xeb, 0xa3, 0x9e,
	0xd4, 0x31, 0x65, 0xe5, 0x7f, 0x4d, 0x03, 0xbf, 0x54, 0xa3, 0x95, 0xc0, 0x27, 0xc0, 0x34, 0xdb,
	0xd2, 0x8f, 0xa2, 0x81, 0xf4, 0xdf, 0x2c, 0x5a, 0xe0, 0x0b, 0x60, 0x5c, 0xd8, 0xfc, 0x44, 0x1c,
	0x2d, 0x56, 0x62, 0x33, 0x6b, 0xdd, 0xbb, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x42, 0xe7, 0x4d,
	0xbc, 0x36, 0x02, 0x00, 0x00,
}
